import { createRequestHandler, type ServerBuild } from 'react-router';
import { applySecurityHeaders } from '../app/lib/portfolio/headers';
// The framework build is generated by npm run build, before Pages compiles functions.
// @ts-ignore generated runtime module
import * as build from '../build/server/index.js';
const handle = createRequestHandler(build as ServerBuild, 'production');
type PagesContext = { request: Request; env: Record<string,unknown>; waitUntil(promise:Promise<unknown>):void; };
export async function onRequest(context:PagesContext):Promise<Response>{
 const response=await handle(context.request,{cloudflare:{env:context.env,ctx:context}});
 const headers=new Headers(response.headers);applySecurityHeaders(headers);
 return new Response(response.body,{status:response.status,statusText:response.statusText,headers});
}
