// Standalone exploration pages. This builder touches design-lab only.
const fs=require('node:fs');const path=require('node:path');const root=__dirname;
const studies=[['theatre','A','Product theatre'],['gallery','B','Spatial collection'],['field','C','Field to interface']];
const arrow='<span class="arrow" aria-hidden="true">↗</span>';
const brand='<a class="brand" href="index.html" aria-label="KashCrop design lab, compare directions"><img src="assets/kashcrop-logo.png" alt="" width="36" height="36"><span class="brand-word">kashcrop<small>Innovations</small></span></a>';
const viewer=`<dialog class="proof-dialog" id="proof-dialog" aria-labelledby="proof-title" aria-describedby="proof-subtitle"><div class="dialog-header"><div><h2 id="proof-title">Project screens</h2><p id="proof-subtitle">A visual look at the product.</p></div><button class="dialog-close" aria-label="Close project viewer" autofocus>×</button></div><div class="dialog-body"><aside class="dialog-info"><p id="proof-description"></p><div class="screen-tabs" id="screen-tabs" role="group" aria-label="Choose a screen"></div><p class="project-origin" id="proof-origin"></p><a class="pill" id="proof-link" target="_blank" rel="noopener noreferrer" hidden>Open public website ${arrow}</a></aside><figure class="dialog-media" id="dialog-media"><img id="proof-image" alt=""><figcaption id="proof-caption" aria-live="polite"></figcaption></figure></div><div class="dialog-footnote">Screen viewer, not an embedded app. Local build captures and illustrative assets are identified above.</div></dialog>`;
for(const [slug,letter,title] of studies){
 const navigation=studies.map(([s,l])=>`<a href="${s}.html" ${s===slug?'aria-current="page"':''}>${l}</a>`).join('');
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="${slug==='gallery'?'#170e12':'#f7f7f6'}"><meta name="description" content="KashCrop Innovations private design exploration: ${title}. Not the deployed portfolio."><title>${letter} / ${title} — KashCrop Design Lab</title><link rel="icon" href="assets/favicon.svg"><link rel="stylesheet" href="base.css"><link rel="stylesheet" href="${slug}.css"><link rel="stylesheet" href="refinements.css"><script src="vendor/gsap.min.js" defer></script><script src="lab.js" defer></script></head><body class="${slug}-page" data-study="${slug}"><a class="skip" href="#main">Skip to work</a><div class="review-bar"><div class="concept-status"><strong>${letter}</strong><span class="review-label">${title} · </span>Design exploration</div><nav aria-label="Design directions">${navigation}<a class="compare-link" href="index.html">Compare ↗</a></nav></div><header class="site-header">${brand}<nav class="site-nav" aria-label="Main"><a class="nav-secondary" href="#work">Selected work</a><a class="nav-secondary" href="#studio">The studio</a><a class="pill" href="mailto:hazik@kashcrop.in">Let’s talk ${arrow}</a></nav></header>${fs.readFileSync(path.join(root,'partials',slug+'-main.html'),'utf8')}<footer class="site-footer"><div class="footer-top"><h2>Let the next good thing<br>start with a conversation.</h2><a href="mailto:hazik@kashcrop.in" class="pill white">Start a project ${arrow}</a></div><div class="footer-bottom"><span>KashCrop Innovations · Kashmir<br>Private exploration. Not deployed. Product images are captures, not interactive apps.</span><nav aria-label="Review"><a href="index.html">Compare directions</a><a href="RESEARCH.md">Sources & credits</a></nav><button class="motion-toggle" type="button" aria-pressed="false">Reduce motion</button></div></footer>${viewer}<noscript><p style="padding:24px">The visual layouts work without JavaScript. The screen viewer and exploration controls need JavaScript. <a href="assets/garden-home.webp">Open a Baghban screen</a> · <a href="assets/phc-home.webp">Open a Plant Health Clinic screen</a></p></noscript></body></html>`;
 fs.writeFileSync(path.join(root,slug+'.html'),html);console.log('Built '+slug+'.html');
}
