const fs=require('node:fs'),path=require('node:path');const {pathToFileURL}=require('node:url');const {chromium}=require('C:/PROJECTS/Tree Passport Platform/node_modules/playwright');const root=__dirname;
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const checks=[];const check=(name,ok,detail=null)=>checks.push({name,ok,detail});try{
for(const width of [1440,768,390,320]){const p=await browser.newPage({viewport:{width,height:960}});await p.goto(pathToFileURL(path.join(root,'index.html')).href);const a=await p.evaluate(()=>({scroll:document.documentElement.scrollWidth,broken:[...document.images].filter(i=>!i.naturalWidth).map(i=>i.src),h1:document.querySelectorAll('h1').length}));check('Comparison/'+width+': layout and images',a.scroll<=width&&a.broken.length===0&&a.h1===1,a);await p.screenshot({path:path.join(root,'evidence',`comparison-${width}.png`),fullPage:width===390});await p.close()}
const p=await browser.newPage({viewport:{width:1440,height:1000}});await p.goto(pathToFileURL(path.join(root,'gallery.html')).href);const view=p.locator('#gallery-viewport');const b=await view.boundingBox(),before=await p.locator('#gallery-world').getAttribute('style');await p.mouse.move(b.x+30,b.y+300);await p.mouse.down();await p.mouse.move(b.x+170,b.y+330,{steps:12});await p.mouse.up();await p.waitForTimeout(150);check('Spatial board: pointer drag pans without opening viewer',before!==await p.locator('#gallery-world').getAttribute('style')&&!await p.locator('#proof-dialog').evaluate(d=>d.open));await p.locator('#reset-gallery').click();await p.locator('.object-phc').click();await p.waitForTimeout(500);for(let i=0;i<14;i++)await p.keyboard.press('Tab');check('Native modal: keyboard focus remains inside',await p.evaluate(()=>!!document.activeElement.closest('#proof-dialog')));await p.keyboard.press('Escape');check('Native modal: Escape restores project focus',await p.evaluate(()=>document.activeElement.matches('.object-phc')&&!document.body.classList.contains('modal-open')));
await p.goto(pathToFileURL(path.join(root,'theatre.html')).href);await p.locator('[data-select="phc"]').click();await p.locator('[data-select="skiie"]').click();await p.locator('[data-select="garden"]').click();await p.waitForTimeout(800);check('Theatre: rapid switching leaves coherent selection',await p.evaluate(()=>document.querySelector('#product-stage').dataset.active==='garden'&&document.querySelector('#front-image').getAttribute('src')==='assets/garden-home.webp'&&document.querySelector('[data-select="garden"]').getAttribute('aria-pressed')==='true'));
await p.locator('[data-select="phc"]').click();await p.locator('.motion-toggle').click();check('Motion: manual reduction respects current project',await p.evaluate(()=>document.documentElement.dataset.motion==='off'&&document.querySelector('#product-stage').dataset.active==='phc'&&Number(getComputedStyle(document.querySelector('#stage-art')).opacity)===1));await p.reload();check('Motion: preference persists on reload',await p.evaluate(()=>document.documentElement.dataset.motion==='off'));await p.close();
// Resolve every local link and media reference from every delivered page.
for(const slug of ['index','theatre','gallery','field']){const page=await browser.newPage();await page.goto(pathToFileURL(path.join(root,slug+'.html')).href);const refs=await page.evaluate(()=>[...document.querySelectorAll('[href],[src]')].flatMap(e=>[e.getAttribute('href'),e.getAttribute('src')]).filter(Boolean));const missing=refs.filter(u=>!/^([a-z]+:|#)/i.test(u)).filter(u=>!fs.existsSync(path.join(root,u.split('#')[0].split('?')[0])));check(slug+': every local link and asset resolves',missing.length===0,missing);await page.close()}
}catch(e){checks.push({name:'Final review completed',ok:false,detail:e.stack})}finally{await browser.close();fs.writeFileSync(path.join(root,'evidence','final-review-results.json'),JSON.stringify({at:new Date().toISOString(),checks},null,2));console.log(JSON.stringify({passed:checks.filter(c=>c.ok).length,failed:checks.filter(c=>!c.ok).length,failures:checks.filter(c=>!c.ok)},null,2));process.exitCode=checks.some(c=>!c.ok)?1:0}})();
