'use strict';
// Local-only design interactions. No forms, analytics, APIs or production mutations.
const PROJECTS={
 garden:{name:'Baghban',subtitle:'Garden Guardians · Orchard services & grower tools',description:'An orchard companion that brings services, seasonal guidance and practical tools into one farmer-facing experience.',origin:'Actual captures from the local review build, 20 September 2026. These do not imply that this version is publicly deployed.',screens:[['Farmer home','garden-home','mobile','The farmer home screen.'],['Orchard setup','garden-service','mobile','The complete orchard-establishment service page. Scroll to inspect.'],['Seasonal calendar','garden-calendar','mobile','The seasonal calendar. Scroll to inspect the complete capture.'],['Variety explorer','garden-varieties','mobile','The variety-explorer screen, captured in the local review build.'],['Desktop view','garden-desktop','wide','The same product at desktop width.']]},
 phc:{name:'Plant Health Clinic',subtitle:'Farmer app · SKUAST-Kashmir',description:'A focused farmer interface for reporting a plant problem, preparing useful photographs and finding a path to expert care.',origin:'Actual captures from the local farmer-app review build, 20 September 2026. Screen navigation here is a viewer, not a live diagnosis or advisory service.',screens:[['Farmer home','phc-home','mobile','The farmer home and report entry point.'],['Report a problem','phc-submit','mobile','The plant-problem submission screen.'],['Photo guidance','phc-guide','mobile','Guidance for photographing a plant problem.']]},
 skiie:{name:'SKIIE',subtitle:'Entrepreneurship & incubation · Public website',description:'A public home for an incubation centre, its people, opportunities and startup ecosystem.',origin:'Public website capture taken from skiie.co.in on 20 September 2026.',url:'https://skiie.co.in/',screens:[['Public homepage','skiie','wide','A capture of the publicly available SKIIE homepage.']]},
 tree:{name:'Tree Passport',subtitle:'Tree identity · Concept artwork',description:'A visual concept for connecting a physical tree, a QR tag and its digital identity. This viewer shows presentation artwork, not a screenshot or proof of a deployed workflow.',origin:'Existing Tree Passport project artwork, reused for this private direction study. Illustrative—not a documentary field photograph or an actual app screen.',screens:[['Tree-tag concept','tree-tag','wide','Illustrative tree-tag concept artwork.'],['Cedar setting','cedar','wide','Existing project artwork used to explore the setting.']]}
};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let userReduced=false;try{userReduced=localStorage.getItem('kashcrop-lab-motion')==='off'}catch{}
const motionQuery=matchMedia('(prefers-reduced-motion: reduce)');const reduced=()=>userReduced||motionQuery.matches;
let motionCleanup=()=>{};
function updateMotion(){motionCleanup();document.documentElement.dataset.motion=reduced()?'off':'on';$$('.motion-toggle').forEach(b=>{b.setAttribute('aria-pressed',String(reduced()));b.textContent=motionQuery.matches?'System: reduced motion':userReduced?'Enable motion':'Reduce motion';b.disabled=motionQuery.matches});
 if(!window.gsap||reduced())return;
 const ctx=gsap.context(()=>{const art=$('#stage-art');if(art)gsap.from(art,{y:32,duration:1.15,ease:'power3.out'});const world=$('#gallery-world');if(world)gsap.from('.object-surface',{y:20,duration:.9,stagger:.07,ease:'power3.out'});});
 const stage=$('#product-stage'),art=$('#stage-art');let enter,move,leave,rect;
 if(stage&&art&&matchMedia('(pointer:fine)').matches){const rx=gsap.quickTo(art,'rotationX',{duration:.75,ease:'power3.out'}),ry=gsap.quickTo(art,'rotationY',{duration:.75,ease:'power3.out'});enter=()=>rect=stage.getBoundingClientRect();move=e=>{if(!rect)return;rx(-((e.clientY-rect.top)/rect.height-.5)*4);ry(((e.clientX-rect.left)/rect.width-.5)*6)};leave=()=>{rx(0);ry(0)};stage.addEventListener('pointerenter',enter);stage.addEventListener('pointermove',move);stage.addEventListener('pointerleave',leave)}
 motionCleanup=()=>{ctx.revert();if(stage&&enter){stage.removeEventListener('pointerenter',enter);stage.removeEventListener('pointermove',move);stage.removeEventListener('pointerleave',leave);gsap.killTweensOf(art);gsap.set(art,{clearProps:'transform,opacity'})}};
}
$$('.motion-toggle').forEach(b=>b.addEventListener('click',()=>{userReduced=!userReduced;try{localStorage.setItem('kashcrop-lab-motion',userReduced?'off':'on')}catch{}updateMotion()}));motionQuery.addEventListener('change',updateMotion);updateMotion();
const dialog=$('#proof-dialog');let currentProject='garden',lastTrigger=null;
function closeViewer(){if(!dialog||!dialog.open)return;dialog.close();document.body.classList.remove('modal-open');if(lastTrigger&&lastTrigger.isConnected)lastTrigger.focus({preventScroll:true});}
function selectScreen(index){const p=PROJECTS[currentProject],s=p.screens[index]||p.screens[0],img=$('#proof-image');img.src=`assets/${s[1]}.webp`;img.alt=`${p.name}: ${s[0]}`;img.className=s[2]==='mobile'?'mobile-capture':'';$('#proof-caption').textContent=s[3];$$('.screen-tab').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));$('#dialog-media').scrollTop=0;}
function openProject(id,index=0,trigger=null){const p=PROJECTS[id];if(!p||!dialog)return;currentProject=id;lastTrigger=trigger||document.activeElement;$('#proof-title').textContent=p.name;$('#proof-subtitle').textContent=p.subtitle;$('#proof-description').textContent=p.description;$('#proof-origin').textContent=p.origin;const tabs=$('#screen-tabs');tabs.replaceChildren();p.screens.forEach((s,i)=>{const b=document.createElement('button');b.className='screen-tab';b.type='button';b.textContent=s[0];b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>selectScreen(i));tabs.append(b)});const link=$('#proof-link');link.hidden=!p.url;if(p.url)link.href=p.url;else link.removeAttribute('href');selectScreen(Math.max(0,Math.min(index,p.screens.length-1)));document.body.classList.add('modal-open');if(!dialog.open)dialog.showModal();if(window.gsap&&!reduced())gsap.fromTo(dialog,{y:20,scale:.985},{y:0,scale:1,duration:.4,ease:'power3.out',clearProps:'transform'});}
if(dialog){$('.dialog-close').addEventListener('click',closeViewer);dialog.addEventListener('cancel',e=>{e.preventDefault();closeViewer()});dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeViewer()});dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');if(lastTrigger&&lastTrigger.isConnected)lastTrigger.focus({preventScroll:true})});}
let suppressGalleryClick=false;
document.addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(!b)return;if(suppressGalleryClick&&b.closest('.gallery-world')){e.preventDefault();return}openProject(b.dataset.open,Number(b.dataset.screen||0),b)});
const stage=$('#product-stage');let stageRevision=0;
function chooseProject(id){const p=PROJECTS[id];if(!p||!stage)return;const revision=++stageRevision;$$('[data-select]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.select===id)));const art=$('#stage-art');const apply=()=>{if(revision!==stageRevision)return;stage.dataset.active=id;art.dataset.project=id;$('#stage-name').textContent=p.name;$('#stage-description').textContent=id==='garden'?'From orchard planning to expert care.':id==='phc'?'A clearer path from concern to care.':'A home for entrepreneurship.';$('#stage-provenance').textContent=id==='skiie'?'Public website capture':'Real screens · Local build';$('#stage-inspect').dataset.open=id;$('#hero-inspect').dataset.open=id;$('#stage-front').hidden=id==='skiie';$('#stage-back').hidden=id==='skiie';$('#stage-skiie').hidden=id!=='skiie';if(id!=='skiie'){const front=$('#front-image'),back=$('#back-image');front.src=`assets/${p.screens[0][1]}.webp`;front.alt=`${p.name}: ${p.screens[0][0]}`;back.src=`assets/${p.screens[1][1]}.webp`;back.alt=`${p.name}: ${p.screens[1][0]}`;}if(window.gsap&&!reduced())gsap.fromTo(art,{y:22,opacity:.55},{y:0,opacity:1,duration:.58,ease:'power3.out',clearProps:'opacity'});else art.style.opacity='1';};if(window.gsap)gsap.killTweensOf(art);apply();}
$$('[data-select]').forEach(b=>b.addEventListener('click',()=>chooseProject(b.dataset.select)));
// Keyboard-native range. A physical context photo is not labeled a before/after result.
const slider=$('#field-reveal');if(slider){const apply=()=>{const value=Number(slider.value);$('#field-hero').style.setProperty('--reveal',`${100-value}%`);slider.setAttribute('aria-valuetext',`${value} percent interface revealed`)};if(innerWidth<560)slider.value='62';slider.addEventListener('input',apply);apply();}
// Drag is optional: all items also exist in an ordinary index.
const viewport=$('#gallery-viewport'),world=$('#gallery-world');
if(viewport&&world){let x=0,y=0,scale=1,drag=null,frame=0,indexMode=false;const clamp=(v,l)=>Math.max(-l,Math.min(l,v));
 const render=()=>{world.style.transform=`translate(calc(-50% + ${x}px),calc(-50% + ${y}px)) scale(${scale})`;frame=0};const schedule=()=>{if(!frame)frame=requestAnimationFrame(render)};
 const fit=()=>{const r=viewport.getBoundingClientRect();if(!r.width)return;scale=innerWidth<560?.66:Math.min(.87,r.width/1470,r.height/765);x=0;y=0;render()};
 const reset=()=>{x=0;y=0;render()};const mode=(on)=>{indexMode=on;viewport.hidden=on;$('#gallery-index').hidden=!on;$('#toggle-gallery').setAttribute('aria-pressed',String(on));$('#toggle-gallery').textContent=on?'Spatial view':'Index view';$('#reset-gallery').hidden=on;$('#gallery-hint').textContent=on?'Choose a project to inspect':'Drag to explore · Select to inspect';if(!on)fit()};
 viewport.addEventListener('pointerdown',e=>{if(e.button!==0)return;drag={px:e.clientX,py:e.clientY,x,y,id:e.pointerId,moved:false};});
 viewport.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.px,dy=e.clientY-drag.py;if(!drag.moved&&Math.hypot(dx,dy)>7){drag.moved=true;viewport.setPointerCapture(e.pointerId);viewport.classList.add('is-dragging')}if(!drag.moved)return;x=clamp(drag.x+dx,460);y=clamp(drag.y+dy,250);schedule();});
 const finish=e=>{if(!drag)return;suppressGalleryClick=drag.moved;drag=null;viewport.classList.remove('is-dragging');if(viewport.hasPointerCapture(e.pointerId))viewport.releasePointerCapture(e.pointerId);setTimeout(()=>suppressGalleryClick=false,100)};
 viewport.addEventListener('pointerup',finish);viewport.addEventListener('pointercancel',finish);viewport.addEventListener('dragstart',e=>e.preventDefault());
 viewport.addEventListener('keydown',e=>{if(e.target!==viewport)return;const keys=['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home'];if(!keys.includes(e.key))return;e.preventDefault();if(e.key==='Home')reset();else{x=clamp(x+(e.key==='ArrowLeft'?65:e.key==='ArrowRight'?-65:0),460);y=clamp(y+(e.key==='ArrowUp'?65:e.key==='ArrowDown'?-65:0),250);render()}});
 $('#reset-gallery').addEventListener('click',reset);$('#toggle-gallery').addEventListener('click',()=>mode(!indexMode));let resizeTimer;addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(!indexMode)fit()},120)});mode(innerWidth<560||reduced());
}

// Keep Tab navigation inside the open viewer, including in local-file Chrome.
if(dialog){
 const preview=$('#dialog-media');preview.tabIndex=0;preview.setAttribute('aria-label','Project screenshot. Scroll to inspect the full image.');
 dialog.addEventListener('keydown',e=>{
  if(e.key!=='Tab'||!dialog.open)return;
  const stops=[...dialog.querySelectorAll('button:not(:disabled),a[href],input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex="0"]')].filter(el=>el.getClientRects().length&&!el.closest('[hidden]'));
  if(!stops.length)return;
  e.preventDefault();const current=stops.indexOf(document.activeElement);const next=(current+(e.shiftKey?-1:1)+stops.length)%stops.length;stops[next].focus();
 });
}
