const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');const {pathToFileURL}=require('node:url');const sharp=require('../node_modules/sharp');const {chromium}=require('C:/PROJECTS/Tree Passport Platform/node_modules/playwright');
const root=__dirname,dir=path.join(root,'evidence');fs.mkdirSync(dir,{recursive:true});
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const results={createdAt:new Date().toISOString(),checks:[],errors:[],screenshots:[]};const check=(name,ok,detail)=>{results.checks.push({name,ok,detail});if(!ok)results.errors.push(name+': '+JSON.stringify(detail))};
try{for(const width of [1440,768,390,320]){for(const slug of ['theatre','gallery','field']){const page=await browser.newPage({viewport:{width,height:width>800?1000:844},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.join(root,slug+'.html')).href,{waitUntil:'load',timeout:20000});await page.waitForTimeout(950);await page.evaluate(()=>document.fonts.ready);const audit=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,h1:document.querySelectorAll('h1').length,broken:[...document.images].filter(i=>i.hasAttribute('src')&&i.getAttribute('src')&&!i.naturalWidth).map(i=>i.getAttribute('src')),bodyHeight:document.body.scrollHeight}));check(`${slug}/${width}: no horizontal overflow`,audit.scroll<=width+1,audit);check(`${slug}/${width}: images loaded`,audit.broken.length===0,audit.broken);check(`${slug}/${width}: heading and runtime`,audit.h1===1&&errors.length===0,errors);
const filename=`${slug}-${width}.png`;await page.screenshot({path:path.join(dir,filename),fullPage:width===390});results.screenshots.push(filename);if(width===1440)await sharp(path.join(dir,filename)).resize({width:1000}).webp({quality:85}).toFile(path.join(dir,`${slug}-preview.webp`));
if(width===1440||width===390){const trigger=page.locator('[data-open]:visible').first();await trigger.click();await page.waitForTimeout(450);check(`${slug}/${width}: viewer opens`,await page.locator('#proof-dialog').evaluate(d=>d.open),null);await page.keyboard.press('Escape');check(`${slug}/${width}: viewer closes and restores focus`,await page.evaluate(()=>!document.querySelector('#proof-dialog').open&&!document.body.classList.contains('modal-open')&&document.activeElement.hasAttribute('data-open')),null);
if(slug==='theatre'){await page.locator('[data-select="phc"]').click();await page.waitForTimeout(750);check(`theatre/${width}: switch updates actual images`,await page.locator('#front-image').getAttribute('src')==='assets/phc-home.webp',null);await page.locator('#stage-inspect').click();await page.waitForTimeout(300);await page.getByRole('button',{name:'Photo guidance',exact:true}).click();check(`theatre/${width}: screen viewer navigation`,await page.locator('#proof-image').getAttribute('src')==='assets/phc-guide.webp',null);await page.screenshot({path:path.join(dir,`viewer-${width}.png`)});await page.keyboard.press('Escape');await page.locator('[data-select="skiie"]').click();await page.waitForTimeout(700);check(`theatre/${width}: desktop project stage`,await page.locator('#stage-skiie').isVisible()&&!await page.locator('#stage-front').isVisible(),null);await page.locator('[data-select="garden"]').click();await page.waitForTimeout(700);}
if(slug==='field'){await page.locator('#field-reveal').focus();await page.keyboard.press('End');check(`field/${width}: keyboard reveal`,await page.locator('#field-reveal').inputValue()==='100'&&await page.locator('#field-hero').evaluate(e=>e.style.getPropertyValue('--reveal'))==='0%',null);await page.keyboard.press('Home');check(`field/${width}: keyboard context`,await page.locator('#field-reveal').inputValue()==='0',null);}
if(slug==='gallery'){let wasIndex=await page.locator('#gallery-index').isVisible();await page.locator('#toggle-gallery').click();check(`gallery/${width}: accessible index toggle`,await page.locator('#gallery-index').isVisible()!==wasIndex,null);if(await page.locator('#gallery-index').isVisible())await page.locator('#toggle-gallery').click();await page.locator('#gallery-viewport').focus();await page.keyboard.press('ArrowRight');const transform=await page.locator('#gallery-world').getAttribute('style');await page.locator('#reset-gallery').click();check(`gallery/${width}: keyboard pan and reset`,transform!==await page.locator('#gallery-world').getAttribute('style'),null);}}
await page.close();fs.writeFileSync(path.join(dir,'review-progress.json'),JSON.stringify(results,null,2));}}
const reduced=await browser.newContext({reducedMotion:'reduce',viewport:{width:390,height:844}});const rp=await reduced.newPage();await rp.goto(pathToFileURL(path.join(root,'gallery.html')).href);check('Reduced motion: honored at startup',await rp.evaluate(()=>document.documentElement.dataset.motion==='off')&&await rp.locator('#gallery-index').isVisible(),null);await reduced.close();
const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});for(const slug of ['theatre','gallery','field']){const p=await nojs.newPage();await p.goto(pathToFileURL(path.join(root,slug+'.html')).href);check(`${slug}: no-JS visible heading and media`,await p.locator('h1').isVisible()&&await p.locator('main img:visible').count()>0,null);await p.close()}await nojs.close();
}catch(e){results.errors.push(e.stack);results.checks.push({name:'Review completed',ok:false,detail:e.message})}finally{await browser.close();fs.writeFileSync(path.join(dir,'review-results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify({passed:results.checks.filter(c=>c.ok).length,failed:results.checks.filter(c=>!c.ok).length,errors:results.errors},null,2));process.exitCode=results.errors.length?1:0}})();
