import { test,expect,type Page } from '@playwright/test';
const endpoint='https://api.web3forms.com/submit';
async function fill(page:Page){await page.getByLabel('Your name',{exact:false}).fill('Portfolio test');await page.getByRole('textbox',{name:/^Email address/}).fill('portfolio-test@example.invalid');await page.getByLabel('A little about the project',{exact:false}).fill('A test enquiry for a working digital platform. Do not send this to any inbox.');}
test.beforeEach(async({page})=>{await page.route(endpoint,route=>route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({success:false})}));});
test('invalid fields are explained before any request is made',async({page})=>{let sent=0;page.on('request',r=>{if(r.url()===endpoint)sent++;});await page.goto('/contact');await page.getByRole('button',{name:'Send your enquiry',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Please check');await expect(page.locator('#inquiry-email')).toHaveAttribute('aria-invalid','true');await expect(page.locator('#inquiry-message')).toHaveAttribute('aria-invalid','true');expect(sent).toBe(0);});
test('service pages preselect the relevant enquiry type',async({page})=>{await page.goto('/services/ai-training');await page.getByRole('link',{name:'Let’s discuss your project'}).click();await expect(page).toHaveURL(/\/contact\?service=ai$/);await expect(page.getByLabel('Applied AI',{exact:true})).toBeChecked();});
test('a failed submission preserves the message and allows a confirmed retry',async({page})=>{await page.goto('/contact');await fill(page);await page.getByRole('button',{name:'Send your enquiry',exact:true}).click();await expect(page.getByRole('alert')).toContainText('could not be delivered');await expect(page.locator('#inquiry-message')).toHaveValue(/Do not send/);await page.unroute(endpoint);let payload:Record<string,unknown>|null=null;await page.route(endpoint,async route=>{payload=route.request().postDataJSON();await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({success:true})});});await page.getByRole('button',{name:'Send your enquiry',exact:true}).click();await expect(page.locator('.inquiry-success')).toBeVisible();expect(payload?.name).toBe('Portfolio test');await expect(page.locator('.inquiry-success')).toBeFocused();await page.getByRole('button',{name:'Send another enquiry'}).click();await expect(page.locator('#inquiry-message')).toHaveValue('');});
test('rate limiting is not mistaken for successful delivery',async({page})=>{await page.unroute(endpoint);await page.route(endpoint,route=>route.fulfill({status:429,contentType:'application/json',body:'{"success":false}'}));await page.goto('/contact');await fill(page);await page.getByRole('button',{name:'Send your enquiry',exact:true}).click();await expect(page.getByRole('alert')).toContainText('too many attempts');await expect(page.locator('.inquiry-success')).not.toBeVisible();});
test('the form disables repeat submission while the request is in flight',async({page})=>{await page.unroute(endpoint);let count=0;await page.route(endpoint,async route=>{count++;await new Promise(resolve=>setTimeout(resolve,600));await route.fulfill({status:200,contentType:'application/json',body:'{"success":true}'});});await page.goto('/contact');await fill(page);await page.getByRole('button',{name:'Send your enquiry',exact:true}).click();await expect(page.getByRole('button',{name:'Sending your enquiry…'})).toBeDisabled();await expect(page.locator('#inquiry-name')).toBeDisabled();await expect(page.locator('.inquiry-success')).toBeVisible();expect(count).toBe(1);});
