import { test,expect } from '@playwright/test';
const routes=['/','/projects','/projects/baghban','/services','/services/blockchain-systems','/about','/contact'];
for(const width of [320,390,768,1024,1440,1920])test(`responsive routes: ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:width<800?844:1000});
 for(const route of routes){await page.goto(route);await expect(page.locator('main h1')).toBeVisible();await page.waitForTimeout(150);const audit=await page.evaluate(()=>({viewport:innerWidth,scroll:document.documentElement.scrollWidth,broken:[...document.images].filter(i=>i.complete&&i.getAttribute('src')&&!i.naturalWidth).map(i=>i.getAttribute('src'))}));expect(audit.scroll,route).toBeLessThanOrEqual(audit.viewport);expect(audit.broken,route).toEqual([]);}
});
test.describe('mobile interactions',()=>{
 test.use({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
 test('mobile navigation reaches actual routes and releases scrolling',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Open navigation'}).tap();await expect(page.getByRole('dialog',{name:'KashCrop Innovations'})).toBeVisible();await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('link',{name:'Work'}).tap();await expect(page).toHaveURL(/\/projects$/);await expect(page.locator('#mobile-menu')).not.toBeVisible();await expect(page.locator('body')).not.toHaveClass(/has-overlay/);});
 test('touch swipe changes the viewed screen without closing the viewer',async({page,context})=>{await page.goto('/?project=baghban&screen=home');await expect(page.locator('#project-viewer')).toBeVisible();const figure=page.locator('.viewer-figure');const r=(await figure.boundingBox())!;const session=await context.newCDPSession(page);const y=r.y+r.height*.45;await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:r.x+r.width*.8,y}]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:r.x+r.width*.25,y:y+2}]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await expect(page.locator('.viewer-screen-heading h3')).toHaveText('Orchard setup');await expect(page.locator('#project-viewer')).toBeVisible();await session.detach();});
 test('the mobile form stays readable and does not overflow',async({page})=>{await page.goto('/contact?service=platform');await expect(page.getByLabel('App or platform',{exact:true})).toBeChecked();expect(await page.locator('#inquiry-name').evaluate(e=>parseFloat(getComputedStyle(e).fontSize))).toBeGreaterThanOrEqual(16);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
});
