import { Link, type MetaFunction } from 'react-router';
import { company, featuredProjects, media } from '~/data/portfolio/catalog';
import { DeviceFrame, BrowserFrame, PageIntro } from '~/components/portfolio/UI';
import { DeliveryMethod } from '~/components/portfolio/signature/DeliveryMethod';
import { Icon } from '~/components/portfolio/Icon';
import { pageMeta } from '~/lib/portfolio/seo';
export const meta:MetaFunction=()=>pageMeta('The studio','Meet KashCrop Innovations: a Kashmir-based product design, engineering and applied AI studio, founded by Hazik Hussain and incubated at SKIIE.','/about');
export default function About(){return <main id="main"><PageIntro eyebrow="The studio" title={<>Rooted in Kashmir.<br/><em>Open to what’s next.</em></>} description="KashCrop Innovations brings product design, engineering and applied AI together. We build useful digital systems around the people who will use them."/>
 <section className="about-canvas section-wrap" aria-label="A selection of KashCrop's work"><div className="about-scene"><div className="about-scene-type" aria-hidden="true">Ideas.<br/>Made useful.</div><div className="about-phone first"><DeviceFrame screen={featuredProjects[0].screens[0]}/></div><div className="about-phone second"><DeviceFrame screen={featuredProjects[1].screens[0]}/></div><BrowserFrame screen={featuredProjects[2].screens[0]} className="about-browser" address="skiie.co.in"/><span className="about-scene-caption">A selection of actual interface captures.</span></div></section>
 <section className="about-intro section-wrap"><h2>One connected<br/>way of thinking.</h2><div><p>The interface is only one part of a product. Its content, data, workflows and infrastructure need the same attention. We work across that whole picture rather than treating design and engineering as separate handoffs.</p><p>Our work spans orchard tools, plant- and fish-health workflows, institutional websites and research interfaces. The common thread is a real problem, a clear experience and a system built around the people doing the work.</p><Link className="underlined" to="/projects">See the work <Icon/></Link></div></section>
 <section className="founder-section section-wrap"><div className="founder-panel"><div className="founder-studio-word" aria-hidden="true">Ideas,<br/>made<br/><em>useful.</em></div><div><p>Founder</p><h2>{company.founder}</h2><span>Product · Design · Engineering</span></div></div><div className="founder-copy"><h2>Close to the problem.<br/>Close to the details.</h2><p>Hazik leads KashCrop’s product and technical work, connecting the interface with the engineering behind it. The practice combines full-stack development and applied AI with a focus on practical, region-specific problems.</p><a className="underlined" href={company.linkedin} target="_blank" rel="noopener noreferrer">Connect on LinkedIn <Icon/></a><div className="incubation-note"><img src={media('skiie-logo.png')} alt="SKIIE" width="56" height="56" loading="lazy"/><div><strong>Incubated at SKIIE</strong><p>SKUAST-Kashmir Innovation, Incubation and Entrepreneurship Centre.</p><a href="https://skiie.co.in/" target="_blank" rel="noopener noreferrer">Explore the centre ↗</a></div></div></div></section>
 <DeliveryMethod/><section className="studio-principles section-wrap"><h2>What guides the work.</h2><div>{[
 ['Start with the workflow.','Understand what people need to do, the context they work in, and the obstacles that get in the way.'],
 ['Show the thinking.','Make interfaces and working product paths visible early, so decisions can be made against something tangible.'],
 ['Build the whole picture.','Bring the content, interface, backend and handover together. Plan support around the product that actually ships.'],
 ].map(([title,body])=><article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></section>
 </main>;}
