import { useEffect, useRef, useState, type FormEvent } from 'react';
import { Link, useSearchParams, type MetaFunction } from 'react-router';
import { company, featuredProjects, media } from '~/data/portfolio/catalog';
import { projectTypes } from '~/data/portfolio/services';
import { Icon } from '~/components/portfolio/Icon';
import { existingFormAccessKey } from '~/lib/portfolio/contact-config';
import { sendInquiry, validateInquiry, type InquiryErrors } from '~/lib/portfolio/inquiry';
import { pageMeta } from '~/lib/portfolio/seo';
export const meta:MetaFunction=()=>pageMeta('Start a project','Tell KashCrop what you’re building. Discuss a website, product platform, applied AI workflow or traceability system.','/contact');
export default function ContactPage(){
 const [params]=useSearchParams();const initialType=projectTypes.some(t=>t.value===params.get('service'))?params.get('service'):null;
 const [selectedServices,setSelectedServices]=useState<string[]>([]);
 useEffect(()=>{setSelectedServices(initialType?[initialType]:[]);},[initialType]);
 const [errors,setErrors]=useState<InquiryErrors>({}),[status,setStatus]=useState<'idle'|'sending'|'success'|'error'>('idle'),[message,setMessage]=useState('');
 const form=useRef<HTMLFormElement>(null),result=useRef<HTMLDivElement>(null),errorSummary=useRef<HTMLDivElement>(null),busy=useRef(false),request=useRef<AbortController|null>(null);
 useEffect(()=>{if(form.current)form.current.noValidate=true;return ()=>request.current?.abort();},[]);
 useEffect(()=>{if(status==='success')result.current?.focus();if(status==='error')errorSummary.current?.focus();},[status]);
 async function submit(event:FormEvent<HTMLFormElement>){
  event.preventDefault();if(busy.current)return;const parsed=validateInquiry(new FormData(event.currentTarget));
  if(!parsed.ok){setErrors(parsed.errors);setStatus('error');setMessage(parsed.errors.form??'Please check the highlighted fields.');requestAnimationFrame(()=>{const name=Object.keys(parsed.errors).find(k=>k!=='form');if(name)document.getElementById(`inquiry-${name}`)?.focus();});return;}
  busy.current=true;setStatus('sending');setErrors({});setMessage('');const controller=new AbortController();request.current=controller;const timeout=setTimeout(()=>controller.abort(),15000);
  try{const response=await sendInquiry(existingFormAccessKey,parsed.inquiry,controller.signal);if(response.ok){setStatus('success');setSelectedServices(initialType?[initialType]:[]);form.current?.reset();}else {setStatus('error');setMessage(response.message);}}
  finally{clearTimeout(timeout);busy.current=false;request.current=null;}
 }
 return <main id="main" className="contact-page"><div className="contact-page-layout section-wrap"><header className="contact-page-intro"><p className="section-note">Start a conversation</p><h1>A real problem.<br/>A good <em>place to start.</em></h1><p>Tell us what you have in mind. A rough idea is enough to begin.</p><div className="contact-details"><a href={`mailto:${company.email}`}><Icon name="mail"/><span>{company.email}</span></a><a href={`tel:${company.phoneLink}`}><Icon name="phone"/><span>{company.phone}</span></a><p>Kashmir, India · Incubated at SKIIE</p></div><div className="contact-project-strip" aria-label="Selected work">{featuredProjects.map(p=><Link key={p.slug} to={`/projects/${p.slug}`} aria-label={`Explore ${p.name}`}><img src={media(p.screens[0].file)} alt={p.name} width={p.screens[0].width} height={p.screens[0].height} loading="lazy"/><span>{p.name}<Icon/></span></Link>)}</div></header>
 <div className="inquiry-panel">{status==='success'?<div className="inquiry-success" ref={result} tabIndex={-1} role="status"><span className="success-mark"><Icon name="check"/></span><p className="section-note">Enquiry received</p><h2>The conversation<br/>starts here.</h2><p>Your message was accepted by our contact service. We’ll review the details and respond using the contact information you shared.</p><Link className="button button-dark" to="/projects">Explore the work <Icon/></Link><button className="underlined" onClick={()=>{setStatus('idle');setMessage('');}}>Send another enquiry</button></div>:<form ref={form} action="https://api.web3forms.com/submit" method="post" onSubmit={submit} aria-labelledby="inquiry-heading">
 <div className="inquiry-panel-heading"><h2 id="inquiry-heading">What are you thinking?</h2><p>Only your name, email and a short project description are required.</p></div>
 <input type="hidden" name="access_key" value={existingFormAccessKey}/><input type="hidden" name="subject" value="A new KashCrop project enquiry"/>
 <div className="form-honeypot" aria-hidden="true"><label htmlFor="inquiry-company">Leave this field blank</label><input id="inquiry-company" name="company" tabIndex={-1} autoComplete="off"/><input name="botcheck" type="checkbox" tabIndex={-1}/></div>
 {status==='error'&&<div className="form-error-summary" ref={errorSummary} tabIndex={-1} role="alert"><strong>Let’s check that.</strong><p>{message}</p></div>}
 <fieldset disabled={status==='sending'} className="inquiry-fields"><legend className="sr-only">Your project enquiry</legend><div className="form-field-pair"><div className="form-field"><label htmlFor="inquiry-name">Your name <span>Required</span></label><input id="inquiry-name" name="name" autoComplete="name" maxLength={120} required aria-invalid={!!errors.name} aria-describedby={errors.name?'error-name':undefined}/>{errors.name&&<p className="field-error" id="error-name">{errors.name}</p>}</div><div className="form-field"><label htmlFor="inquiry-email">Email address <span>Required</span></label><input id="inquiry-email" name="email" type="email" autoComplete="email" maxLength={254} required aria-invalid={!!errors.email} aria-describedby={errors.email?'error-email':undefined}/>{errors.email&&<p className="field-error" id="error-email">{errors.email}</p>}</div></div>
 <div className="form-field-pair"><div className="form-field"><label htmlFor="inquiry-organization">Organisation <span>Optional</span></label><input id="inquiry-organization" name="organization" autoComplete="organization" maxLength={180}/></div><div className="form-field"><label htmlFor="inquiry-phone">Phone or WhatsApp <span>Optional</span></label><input id="inquiry-phone" name="phone" type="tel" autoComplete="tel" maxLength={50}/></div></div>
 <fieldset className="project-type-field"><legend>What can we help with?</legend><div className="project-type-options">{projectTypes.map(type=><label key={type.value}><input type="checkbox" name="services" value={type.value} checked={selectedServices.includes(type.value)} onChange={event=>setSelectedServices(current=>event.target.checked?[...current,type.value]:current.filter(value=>value!==type.value))}/><span>{type.label}</span></label>)}</div></fieldset>
 <div className="form-field"><label htmlFor="inquiry-message">A little about the project <span>Required</span></label><textarea id="inquiry-message" name="message" rows={5} minLength={10} maxLength={5000} required placeholder="What needs to work? Who is it for? Tell us where you are now and what you’re hoping to build." aria-invalid={!!errors.message} aria-describedby={errors.message?'error-message':undefined}/>{errors.message&&<p className="field-error" id="error-message">{errors.message}</p>}</div>
 <div className="form-field-pair"><div className="form-field"><label htmlFor="inquiry-budget">Budget range <span>Optional</span></label><select id="inquiry-budget" name="budget" defaultValue=""><option value="">Let’s discuss it</option><option>Under ₹1 lakh</option><option>₹1–3 lakh</option><option>₹3–5 lakh</option><option>₹5 lakh or more</option></select></div><div className="form-field"><label htmlFor="inquiry-timeline">When are you hoping to start? <span>Optional</span></label><select id="inquiry-timeline" name="timeline" defaultValue=""><option value="">Flexible / exploring</option><option>As soon as practical</option><option>Within 1–3 months</option><option>Later this year</option></select></div></div>
 <p className="form-privacy">We’ll use these details to respond to your enquiry. Submission is handled by Web3Forms. <Link to="/privacy">How we handle your information</Link>.</p><button className="button button-dark inquiry-submit" type="submit" disabled={status==='sending'}>{status==='sending'?'Sending your enquiry…':'Send your enquiry'}<Icon name={status==='sending'?'right':'arrow'}/></button><p className="form-direct-note">Prefer email? <a href={`mailto:${company.email}`}>Write to us directly ↗</a></p>
 </fieldset></form>}</div></div></main>;
}
